name: iOS Build (Final Solution)

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  ios-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Setup Expo CLI
      run: |
        npm install -g @expo/cli
        
    - name: Check initial state
      run: |
        echo "=== Initial iOS folder ==="
        ls -la ios/ || echo "iOS folder not found"
        
    - name: Check for existing Podfile
      id: check_podfile
      run: |
        if [ -f "ios/Podfile" ]; then
          echo "podfile_exists=true" >> $GITHUB_OUTPUT
          echo "=== Podfile found, using existing iOS project ==="
        else
          echo "podfile_exists=false" >> $GITHUB_OUTPUT
          echo "=== No Podfile found, need to generate iOS project ==="
        fi
        
    - name: Generate iOS project (if Podfile missing)
      if: steps.check_podfile.outputs.podfile_exists == 'false'
      run: |
        echo "=== Generating iOS project with expo prebuild ==="
        npx expo prebuild --platform ios --clean --no-install
        
    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Install CocoaPods dependencies
      run: |
        cd ios
        echo "=== Installing CocoaPods dependencies ==="
        pod install --repo-update --verbose
        
    - name: Verify iOS project setup
      run: |
        echo "=== iOS project structure ==="
        ls -la ios/
        echo "=== Podfile verification ==="
        cat ios/Podfile | head -10
        echo "=== Workspace verification ==="
        ls -la ios/*.xcworkspace
        
    - name: Build iOS project for simulator
      run: |
        cd ios
        echo "=== Building iOS project ==="
        xcodebuild -workspace PolyglotKey.xcworkspace \
                   -scheme PolyglotKey \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 14' \
                   build CODE_SIGNING_ALLOWED=NO
        
    - name: Success - Upload iOS build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-success
        path: |
          ios/
          
    - name: Failure - Upload logs for debugging
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-failure-logs
        path: |
          ~/Library/Logs/DiagnosticReports/
          *.log 